### ISSUE TITLE
Steps to first major version

### ISSUE THREAD

**Issue by spruce** [piceaTech/ember-rapid-forms#1]
Things which need to be done to reach next version
* [x] implement showAllErrors + Docs (see: https://github.com/indexiatech/ember-forms/pull/52) (PR in the works)
* [x]  horizontal glitch fix
* [x]  address most issues from https://github.com/indexiatech/ember-forms/issues
* [x]  include pull requests from https://github.com/indexiatech/ember-forms/pulls
* [x]  layout bug fix —> don't use Layoutname but layout instead
* [x]  more tests
  * [x] Checkbox test
  * [x] Input test
  * [x] Select test
  * [x] Control within label test
  * [x] Mixin's tests
  * [x] Util's tests
* [x] tests for on keyup pr
* [x] Support for `DS.Errors`

**Comment by pedrokiefer** [comment]
I've migrated most of the tests from the old coffeescript version.

I think we should rename the source files to keep in line with ember conventions too. ie: 
has_property.js => has-property.js
control_help.js => control-help.js

**Comment by spruce** [comment]
Sure. Can You Point me to the page where it states that?

**Comment by pedrokiefer** [comment]
@spruce http://www.ember-cli.com/#dasherized-file-and-folder-names-are-required
I think @technomage PR #10 covers most of the renaming. Missing only the mixins. 

Do you have a plan of attack for covering all the items on this to do list? 

I would probably start with getting #10 in, then unit tests, PR requests from `ember-forms` and finally fix issues in `ember-forms` by adding new tests first.

**Comment by spruce** [comment]
Thanks:)

Not quite yet.

Sounds about right. 

Thanks for the help again. @pedrokiefer @technomage @fivetwentysix . Pretty apreciated.

**Comment by pedrokiefer** [comment]
@spruce can you update your patch for showAllErrors with a unit test for it? 

I'll try to compile which PR and issues we need to address next.

**Comment by spruce** [comment]
Sure. Will try to get it done in the next 24 hrs.

**Comment by pedrokiefer** [comment]
Do we need ember-cli-watson as a dependency?

**Comment by spruce** [comment]
Probably not. I think I tried to use it to switch to non-prototyp computed properties

**Comment by spruce** [comment]
showAllErrors was actually already possible. Not with that name but showErrorsOnRender
