### ISSUE TITLE
Validation errors not displayed on submit

### ISSUE THREAD

**Issue by josefguenther** [piceaTech/ember-rapid-forms#100]
When the `submit` action is called, the validations are run. If they fail, the upstream action will not be called. However, if no fields have been edited (so no validations are shown), every field will silently fail and not display the validation message.

The way around this would be specifying `showErrorsOnRender`, but that will display the errors on render which is not what I want.

I want the errors to display on submit. There should be a new property with a default `true` on the `em-form` component:
```
  showErrorsOnSubmit: true,
```

This should not be that hard to do, and I could throw together a PR if you want...

**Comment by GCorbel** [comment]
I think your right. A PR is welcomed! Thanks.

**Comment by spruce** [comment]
Closed as of your PR
