### ISSUE TITLE
em-checkbox cannot be disabled

### ISSUE THREAD

**Issue by josefguenther** [piceaTech/ember-rapid-forms#101]
Specifying `disabled` on an `em-checkbox` component does not produce the desired effect.

```
{{em-checkbox label="Check this" property="checkThis" disabled="disabled" }}
```

Produces this:

```
<div class="ember-view checkbox" disabled="disabled" id="ember1098">
  <label class="ember-view control-label" for="checkThis-ember1098" id="ember1101">
    <input class="ember-view" id="checkThis-ember1098" type="checkbox">
    Check this
  </label>
</div>
```

As you can see, the disabled attribute is set on the parent DIV but not on the INPUT. On a normal `em-input`, it is set on both the div and the input, and works correctly.

**Comment by spruce** [comment]
Thanks for catching that! Do you wanna create a PR?
