### ISSUE TITLE
Weird behavior of errors when using input.

### ISSUE THREAD

**Issue by GCorbel** [piceaTech/ember-rapid-forms#102]
I have a strange issue.

I do something like this : 

```
model.get('errors').add('name', 'test')
model.get('errors.name') # gives test, it's normal
model.set('name', 'test')
model.get('errors.name') # gives test, should gives null
```

This is related to ERF because when I comment [this line](https://github.com/piceaTech/ember-rapid-forms/blob/master/addon%2Fmixins%2Fhas-property-validation.js#L14) it works. The bug happens only when an input is created.

I'm not able to reproduce the bug outside ERF.

Does someone have an idea? Can someone reproduce this bug?

**Comment by spruce** [comment]
In your code snippet why should the last line return null? Do you have some kind of validation in place?


P.S.: I think apart from your problem with that line we should try to refactor it away from bindings

**Comment by GCorbel** [comment]
I have this behavior with a clean model. It do this with standard Ember and ERF change it.

What is your suggestion to replace bindings? There is probably something to do with Computed Properties.

**Comment by GCorbel** [comment]
@spruce I think we can use http://emberjs.com/api/#method_defineProperty to add computedProperties. I don't know if these is a better way. Do you have suggestions?

**Comment by spruce** [comment]
Can we close this issue?

**Comment by spruce** [comment]
Seems so :)
