### ISSUE TITLE
Option to have nested inline row inside a horizontal form (with label on left)

### ISSUE THREAD

**Issue by djsegal** [piceaTech/ember-rapid-forms#105]
something like this:

<img width="764" alt="screen shot 2016-04-14 at 7 28 38 pm" src="https://cloud.githubusercontent.com/assets/3156114/14546958/392e3fb6-0277-11e6-9531-57def7a98d76.png">

**Comment by GCorbel** [comment]
Hl

Can you try something like : 

```
{{#em-form-group label="nested"}}
your inputs...
{{/em-form-group}}
```

Is it correct?

**Comment by djsegal** [comment]
I went a different route with it. I might come back to the problem in the future
