### ISSUE TITLE
update ember-try config

### ISSUE THREAD

**Issue by spruce** [piceaTech/ember-rapid-forms#106]
As of late there exists the possibility to automatically add new versions to the test scenarios. See : https://github.com/ember-cli/ember-try#configuration-files . Thing is it will no longer be possible to run these as different builds on travis which means we will have longer build times. Also I haven't looked into how we can than test single ember versions locally.

What do you think about upgrading? @piceaTech/forms

**Comment by GCorbel** [comment]
I agree the the upgrade but I think a refactoring is welcomed but I don't have the time to do it.

**Comment by spruce** [comment]
Running all tests in parallel would lead to times longer than 20 minutes. Which I think is not acceptable. That's why I'm gonna close it for now.
