### ISSUE TITLE
Cannot get build working

### ISSUE THREAD

**Issue by josefguenther** [piceaTech/ember-rapid-forms#107]
I'm trying to write a new test.

I installed all the node and bower components with `npm install` and `bower install`. I get errors for `utf-8-validate` and `bufferutil`. Node-gyp terminates with errors. I think they need to be updated.

I tried this in package.json with no effect:
```
    "bufferutil": "^1.2.1",
    "utf-8-validate": "^1.2.1",
```

I'm not sure if it's essential to get those working. At any rate, I cannot get the build working.

```
ember b
```
```
Error: ENOENT: no such file or directory, stat 'D:\GIT\josefguenther\ember-rapid-forms\tmp\broccoli_merge_trees-input_base_path-v5CKf7yV.tmp\3\dummy\config'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
...............
```

Have you got this working recently?

Is there any benefit to not updating the packages? I wonder if all the ember packages shouldn't be updated. They are significantly out of date.

**Comment by spruce** [comment]
What exactly are the error messages? This project doesn't directly depend on those two. For me it is building. Node-gyp is nasty on windows. Can't help you there because I'm only working on MacOSX.

No benefits for not upgrading. I only don't have the time to do it right now. PR for that would be welcome.

**Comment by josefguenther** [comment]
node-gyp is indeed nasty. Not my first issue with it. I believe that it's `ember-cli-_something_` that's causing this with dependencies. Since it's all old (old) versions, I really don't care to check at this point, especially if you're fine with an upgrade. I got Travis working (see my PR).

Ok. Only issue is, the tests on travis check against 2.0+. You mention you support 1.13+. I would hesitate to upgrade the project unless you're committed to supporting only 2.0+....

Honestly, the source code is not very pretty IMHO. It could use some updating as well.

I'm just not sure I would be ready to tackle a project like this right now. I'll give it some thought.

**Comment by GCorbel** [comment]
@josefguenther we already know the project needs major refactoring. It's not a good period for me to do it.

**Comment by spruce** [comment]
@josefguenther But you didn't upgrade the package.json in your PR or have I overlooked sth?

Can you point me to the place where it says 1.13+ because we only want to support 2.x beginning from some month ago. Because it was originally forked and the original stays with 1.13.

**Comment by josefguenther** [comment]
Version Support


The Plugin starting from version 1.0.0 doesn't support ember versions below 1.13. If you need support for this work with a version < 1.0.0 or alternativly use https://github.com/indexiatech/ember-forms


Josef


-----


Sent from my android phone.






On Wed, Apr 20, 2016 at 1:52 PM -0700, "Felix Fichte" <notifications@github.com> wrote:












@josefguenther But you didn't upgrade the package.json in your PR or have I overlooked sth?



Can you point me to the place where it says 1.13+ because we only want to support 2.x beginning from some month ago. Because it was originally forked and the original stays with 1.13.

**Comment by spruce** [comment]
Yeah. That's technically correct. I rewrite it to state clearly that we dropped support for 1.13 too.

**Comment by spruce** [comment]
I got the build working again. So this should be a non issue. Re-open if I'm wrong
