### ISSUE TITLE
Supporting nested hasMany relations in a form

### ISSUE THREAD

**Issue by djsegal** [piceaTech/ember-rapid-forms#111]
I can't find how to do nested resources from the following resource: 
+ [em-form-multi-models-test.js](https://github.com/piceaTech/ember-rapid-forms/blob/5b81373b9799b7e2df3126f690fd02b9219739c4/tests/unit/components/em-form-multi-models-test.js)
+ [issue #69](https://github.com/piceaTech/ember-rapid-forms/issues/69)

Is there a way to do it without getting really creative? (like flattening the tree structure into a hash)

-----------

A similar example to #69 would be: 

```
{{#each model.contacts as |contact|}}
  {{em-input property="contact.email"}}
  {{#each contact.onlineProfiles as |onlineProfile|}}
    {{em-input property="onlineProfile.username"}}
    ... 
      ...
    ...
  {{/each}}
{{/each}}
```

**Comment by djsegal** [comment]
A similar example to #69: 

```
{{#each model.contacts as |contact|}}
  {{em-input property="contact.email"}}
  {{#each contact.onlineProfiles as |onlineProfile|}}
    {{em-input property="onlineProfile.username"}}
  {{/each}}
{{/each}}
```

**Comment by GCorbel** [comment]
You can do something like this : 

```
{{#each model.contacts as |contact i|}}
  {{em-input cid=(contact "contact-" i) model=contact property="email"}}
  {{#each contact.onlineProfiles as |onlineProfile j|}}
    {{em-input cid=(contact "contact-" i "-online-profile-" i) model=onlineProfile property="username"}}
    ... 
      ...
    ...
  {{/each}}
{{/each}}
```

I think it will work.

**Comment by djsegal** [comment]
You the man, Corbel. I'll check it out

**Comment by djsegal** [comment]
for future reference, there are a few things I had to do to get the above code by @GCorbel to work.
+ fix helper name type: `(contact ...` to `(concat ...`
+ fix indexing typo at end of cid:  `... online-profile-" i)` to `... online-profile-" j)`
+ append field name to prevent cid name collisions:
   - change `{{em-input cid=(contact "contact-" i) model=contact property="email"}}`
   - to `{{em-input cid=(contact "contact-" i "-email") model=contact property="email"}}`

**Comment by GCorbel** [comment]
You're right. Thanks for corrections!
