### ISSUE TITLE
Allow custom actions on <select /> change

### ISSUE THREAD

**Issue by hectorh30** [piceaTech/ember-rapid-forms#112]
Hi there,

I'm trying to create an `em-select`that's not going to be bound a model property, but to a controller property (to aid -filter- selection of a model property).

I want to trigger a custom action (a controller action) when this particular `em-select` changes, and I found out the inner commponent (`html-select`) has an extension point that seems to be exactly for that:

https://github.com/piceaTech/ember-rapid-forms/blob/master/addon/components/html-select.js#L61

Problem is it uses a local property (`this.get('action');`), which I'm not able to define when I use the `em-select` in a template (as far as I can tell).

¿Shouln't it use `mainComponent.action` so that I can define that action when I use the `em-select` component? (that would be sweet).

¿Whats the use case for that extension point using a local `action` property?

**Comment by GCorbel** [comment]
Sorry for late answer. I'm not sure but I think you can do something like this : 

    {{em-select label="Fruits:" content=fruitOptions optionValuePath='id' optionLabelPath='name' action='controllerAction'}}

Is it working?

**Comment by spruce** [comment]
Closing as of inactivity.

**Comment by vigpatrick** [comment]
you can use:

`change=(action 'actionName)`
