### ISSUE TITLE
How can I make a form-level error?

### ISSUE THREAD

**Issue by erichonkanen** [piceaTech/ember-rapid-forms#113]
Hello,

Checking this package out and I'm wondering if it's possible to set a form-level error? Basically in my controller if an api call returns a server error, I want to display a generic message to the user but I'm not sure how to do that with this package?

I was able to do something like this:

```
          {{#em-form model=this}}
            {{em-input type="password" property="currentPassword" placeholder="enter your current password" label="Current Password"}}
            {{em-input type="password" property="newPassword1" placeholder="enter a new password" label="New Password"}}
            {{em-input type="password" property="newPassword2" placeholder="enter the password again" label="Confirm New Password"}}
            {{#if errorMessage}}
            {{errorMessage}}
            {{/if}}
```

but then how can I do something like have that error message be removed once a user begins typing in any of the fields?

**Comment by GCorbel** [comment]
You do have that error message removed once the user enter something in a field? I don't know what the best way but I think you can observe changes on the model and clean `errorMessage` if it change. What you think?
