### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by GCorbel** [piceaTech/ember-rapid-forms#117]
In order to release the 1.0 version, I want to refactor and improve the code. I think it's a little bit complicated. I don't like the fact than there is too many yields in template because but I tried to start the refactoring and I don't succeed. 

If you have ideas, please let me know. @spruce you're opinion is appreciated.

**Comment by spruce** [comment]
I'm really in favor of doing that. But as you said it is quite a task. Maybe we can make some more work on the PR https://github.com/piceaTech/ember-rapid-forms/pull/75 

It is not pretty there either but I think it is generally a good start.

**Comment by spruce** [comment]
Another thought while I'm at it. I want to create a graphical representation of how the components are nested inside each other to make it clearer to everyone (including me) how it works. For now it is a nice Frankenstein monster 👊

**Comment by GCorbel** [comment]
I totally agree for a graph.

**Comment by GCorbel** [comment]
I'm thinking about the graph but I think we need it because it's complicated and we have a structural problem. I think we need to search if we find solutions to those problems. Personally, I don't know. If you have suggestions, I'm ready to work on it.

**Comment by spruce** [comment]
For now we mirror quite closely the way bootstrap builds its forms. We might be able to create bigger components/templates without loosing some flexibility but we loose DRYness because then we will have in many components the same div's and such.

**Comment by pedrokiefer** [comment]
+1 for refactoring and cleaning it up.
The templates have been a pain since the beginning, way too many if's, yield's and parameters passing around.

**Comment by spruce** [comment]
I think we can close this issue, right @GCorbel ?
