### ISSUE TITLE
Using `deprecatingAlias` triggers additional deprecation warnings when used as instructed

### ISSUE THREAD

**Issue by luketheobscure** [piceaTech/ember-rapid-forms#118]
Attempting to use `deprecatingAlias` as instructed by the [docs](http://emberjs.com/api/classes/Ember.computed.html#method_deprecatingAlias) triggers additional deprecation warnings. In order to use it without triggering additional deprecation warnings, you have to pass in an object with an `id` and an `until` property:

`oldAndBusted: computed.deprecatingAlias('newHotness', { id: 'foo', until: '1.42' });`

**Comment by GCorbel** [comment]
Deprecation warnings will be removed a near future as you can see in the PR #115 I close this issue.

**Comment by luketheobscure** [comment]
Somehow managed to file that issue on the wrong project! Sorry about that.
