### ISSUE TITLE
Question: Have people set up em-text to use ivy-codemirror?

### ISSUE THREAD

**Issue by djsegal** [piceaTech/ember-rapid-forms#129]
i was just wondering if anyone had already attempted this
- addon in question: [ivy-codemirror](https://github.com/IvyApp/ivy-codemirror/)
- codemirror allows you to transform textareas into code editors.

**Comment by spruce** [comment]
I can only speak for myself: I've not done anything like that.

Also: Please keep the issue section for real bugs. Such things would be better suited on Stackoverflow or alike.

**Comment by GCorbel** [comment]
I never did this but I think you can use the `em-custom-input` component. Let us know if you have a bug.

**Comment by spruce** [comment]
As it's a question. I gonna close this one.
