### ISSUE TITLE
support 'readonly' attribute for input fields

### ISSUE THREAD

**Issue by thomas-atwood** [piceaTech/ember-rapid-forms#132]
Essentially a second vote for the 'disabled' support in an earlier request.  
I would also like to second the request for supporting the set of related objects (through has-many declaration on the model) as the options in a drop-down select — with an option for preventing the user from editing/deleting these links through the form.  
Nice component: It significantly cleans up the large set of input forms I was creating with Bootstrap-sassy.  
If you haven't already, you might take a look at the Rails simple-form gem for additional customization ideas.

**Comment by GCorbel** [comment]
Hi, disabled should work now. Can you try the master branch?

I started to contribute because I love simpe-form.

**Comment by spruce** [comment]
Closing as of inactivity.
