### ISSUE TITLE
version of rapid-forms for Googles Material Design rather than Bootstrap? 

### ISSUE THREAD

**Issue by thomas-atwood** [piceaTech/ember-rapid-forms#133]
Love to have a prepackaged version of this for use with Material Design scss and javascript.

**Comment by GCorbel** [comment]
I agree but it will be a big job. We have to think about that.

**Comment by danconnell** [comment]
Foundation would be nice too

**Comment by spruce** [comment]
I think @GCorbel is right. It will be quite a big undertaking. Also our current structure is adapted to the element structure bootstrap requires. I think it would be best if it will be either forked or maybe rewrite the core to use and abstract model which then uses bootstrap/material/foundation

**Comment by spruce** [comment]
As it's a question. I gonna close this one.
