### ISSUE TITLE
Changing API to use contextual components before 1.0 release?

### ISSUE THREAD

**Issue by taras** [piceaTech/ember-rapid-forms#136]
Once 1.0 is released, we'll be stuck with API that relies on `parentView`. What are your thoughts about changing the API to use contextual components before 1.0?

The new syntax would look like this.

``` hbs
{{#form model as |em|}}
  {{em.input 'someProperty'}}
{{/form}}
```

Contextual components API would remove the necessity for `parentView` and allow nesting input fields in template block of another component.

``` hbs
{{#form model as |em|}}
  {{#some-other}}
    {{em.input 'someProperty'}}
  {{/some-other}}
{{/form}}
```

It would likely require an AST transform to help those who're using the current API upgrade to new yielding syntax.

**Comment by taras** [comment]
Looks like this was already proposed in #58

**Comment by GCorbel** [comment]
It sounds good but it will take time to do. Are you available to do a PR?

**Comment by spruce** [comment]
Ok, so I'm gonna invest some time over the next few days for making ember-rapid-forms use contextual components.

**Comment by spruce** [comment]
@taras see my work on that matter in PR #138

**Comment by spruce** [comment]
@taras What you say to #138 ?

**Comment by taras** [comment]
@spruce it looks great!

**Comment by spruce** [comment]
Purfect. 🐱
