### ISSUE TITLE
Error message not displaying when validation fails

### ISSUE THREAD

**Issue by ScottSmix** [piceaTech/ember-rapid-forms#14]
I am using ember-rapid-forms 0.6.2. Comparing files, I have the same version of all the key dependencies (like ember-cli, ember, ember-data, ember-validations, etc).

Two related issues:

Issue 1: The error message text is not showing up even though the model.errors.<propertyName> contains errors (and consequently the errors array contains values) because the validations have failed.

Issue 2: When the form is first displayed, the help text is not showing. You have to focus out for the help text to display. The help text is not overridden if there are errors (because validation(s) have failed).

I am not expert. I spent several hours trying to isolate the problem. Anyone else having this problem? If not, any clues what I could be doing wrong?

**Comment by ScottSmix** [comment]
I believe I found the problem. The mainComponent is not being passed to the em-form-control-help in addon/templates/components/form-group.hbs. The bottom lines of the file should be:
```
...
{{!Currently no errors when layout is inline}}
{{#unless form.isInline}}
    {{#if canShowErrors}}
        {{em-form-control-help text=help viewName=helpViewName mainComponent=mainComponent}}
    {{/if}}
{{/unless}}
```
However, there is another issue:

When you first transition to a form, none of the help text is displayed even when a control is focused for the first time. You seem to have to change the input and focus out of the input before help and error messages start to display.

**Comment by ScottSmix** [comment]
Not sure it's the right change, but the last tweak was to modify the addon/components/em-form-group.js file by triggering showing of errors based on focus-in. This fixed the additional issue called out in my very last post. I added this snippet:
```
...
  /*
  Listen to the focus-in and trigger the display of errors
   */
  focusIn: function() {
    return this.set('canShowErrors', true);
  },
...
````
Things seem to be better now.

**Comment by pedrokiefer** [comment]
I'm trying to understand your use case:
You have a model filled with some wrong data and you need to display a form for correcting this data? When the form shows up you want to all the wrong fields to be highlighted and display the error message.

```javascript
test('a form display errors when rendered', function(assert) {
  assert.expect(1);
  var component = this.subject({
    targetObject: FormController.create(),
    model: somePerson,
    template: Ember.HTMLBars.compile('{{em-input property="name"}}')
  });

  Ember.run(() => {
    component.get('model').set('isValid', false);
    component.get('model').set('errors.name', Ember.A(['name!']));
  });

  this.render();

  Ember.run(() => {
    assert.equal(Ember.$(component.element).find('div:contains("name!")').length, 1, "Found help text on form");
  });
});
```
Something like this?

Your first patch is definitely needed, but I'm not so sure about how to handle this behaviour you are asking. I tried to make the form react to changes on model errors, but an empty model will have `errors` set, and all the fields would render displaying errors, something we don't want to happen.

Would a flag work for you, something like `showErrorsOnRender` on `{{em-form}}`?

**Comment by ScottSmix** [comment]
Thank you for the response and sorry for the confusion. I was co-mingling two use cases. I think two flags would be on {{em=form}} would be best:

1. To handle the case where invalid data might be loaded into the form (in the case of editing existing data), your suggested flag "showErrorsOnRender" would work. The benefit to the user is they can immediately see the inputs they need to fix.

2. Another flag to handle the case where canShowErrors is set to true when a control is first focused. This case is useful for adding and changing data. I don't want to have to exit the input in order to kick start the validation and show errors. So the code would look like:
```
// addon/components/em-form-group.js
...
  /*
  Listen to the focus-in and trigger the display of errors
   */
  focusIn: function() {
    if (this.get('form.showErrorsOnFocusIn')) {
      this.set('canShowErrors', true);
    }
    return true;
  },
...
```

**Comment by pedrokiefer** [comment]
@ScottSmix added a pull request with this features and unit test for them. If this doesn't break anything, we can merge.

**Comment by ScottSmix** [comment]
@pedrokiefer awesome! Thank you!

**Comment by ScottSmix** [comment]
@pedrokiefer can you get this in too? Found a bug where the v_icon was not displaying because the mainComponent was not referenced. There might be a better way, but the fix that seems to work fine is in addon/templates/components/form-group.js:
```handlebars
{{#if v_icons}}
    <span class="form-control-feedback"><i class={{mainComponent.v_icon}}></i></span>
{{/if}}

```

**Comment by pedrokiefer** [comment]
Sure! I will fix this too, also want to get basic unit tests for this kind os thing, so in the future we don't get regressions.

**Comment by pedrokiefer** [comment]
@ScottSmix pushed a fix and a few test cases for form-group and form-group-control

**Comment by ScottSmix** [comment]
@pedrokiefer awesome!! Thanks!

**Comment by pedrokiefer** [comment]
Have we fixed all the issues on this thread? Can we close it now?

**Comment by spruce** [comment]
I think so. Right? @ScottSmix

**Comment by ScottSmix** [comment]
Yes, all issues on this thread are handled/merged. Thank you very much!
