### ISSUE TITLE
object in path "mainComponent.model" and deprecation id: ember-rapid-forms.yielded-form

### ISSUE THREAD

**Issue by haldiggs** [piceaTech/ember-rapid-forms#155]
just upgraded from Ember 2.6 to 2.11 so I do expect a few issues. 

ember-rapid-forms is beta12.  
ember-validations are 2.0.0-alpha.5

As soon as a field validation is attempted we get an error for each field "Property set failed: object in path "mainComponent.model" could not be found or was destroyed"

I'm not sure if the issue is Ember-Validations or the ember-forms at this point. 
All forms are throw a warning "DEPRECATION: Please use the new form.input helper defined in 1.0.0beta10 [deprecation id: ember-rapid-forms.yielded-form]" and I am not sure what the correction is. I tried looking at the docs but cannot see any difference.

Has anybody experienced this after upgrading?

**Comment by GCorbel** [comment]
Can you try with the branch in this PR : #146 

Just use this version : GCorbel/ember-rapid-forms#refactoring
