### ISSUE TITLE
new form.input helper defined in 1.0.0beta10

### ISSUE THREAD

**Issue by haldiggs** [piceaTech/ember-rapid-forms#157]
is this no longer valid?
    {{em-input label="First Name" property="firstName" cid="FID"}}
I am getting the deprecation warning saying I need to use the new form.input helper defined in 1.0.0beta10 [deprecation id: ember-rapid-forms.yielded-form] but I don't see anything in the documentation http://piceatech.github.io/ember-rapid-forms/#/controls/input , this surely looks like a breaking change but all I see under the beta10 tag is the source code which I'd rather not delve into. You guy are the pros.

**Comment by spruce** [comment]
Yes. Documentation is a little outdated. In the next few days I will update it. new form is like this:
```
{{#em-form as |form|}}
{{form.input label="First Name" property="firstName" cid="FID"}}
{{/em-form}}
```

**Comment by haldiggs** [comment]
ok so I see the input now but the values still don't seem to flow. Did anything int he stup change as well?

    import EmberValidations from 'ember-validations';

**Comment by spruce** [comment]
Can you show some more of your code or else it is really hard to tell what is going on
