### ISSUE TITLE
After refactor, page refreshes on form submit in specific cases

### ISSUE THREAD

**Issue by slannigan** [piceaTech/ember-rapid-forms#160]
After the refactor which got merged yesterday (https://github.com/piceaTech/ember-rapid-forms/pull/146), some types of form submission no longer works, including the method of form submission recommended in the Ember Rapid Forms docs (http://piceatech.github.io/ember-rapid-forms/#/controls/custom-submit)

The bug which occurs is, when the "Submit" button is clicked, the submit action doesn't run and the page gets force refreshed.

If this is an unintentional bug, I'd be happy to help look into it. However, there have been a lot of undocumented changes lately, so I wanted to first check if the choice to not support some form types is intentional.

You can experience the bugs using this repo I created. It contains the below form examples.  https://github.com/slannigan/em-forms-refactor-bug

--------------------------
Forms which work:

submitButton=true, action='submit'
```
{{#em-form model=model action='submit' as |form|}}
  ...
{{/em-form}}
```
submitButton=false, no action, and a button with action='submit'
```
{{#em-form model=model submitButton=false as |form|}}
  ...
  <button {{action='submit'}}>
    Submit
  </button>
{{/em-form}}
```
----------------------
Forms which worked previously, but now exhibit the refresh bug:

submitButton=false, action='submit', and a button with type='submit'
```
{{#em-form model=model submitButton=false action='submit' as |form|}}
  ...
  <button type='submit'>
    Submit
  </button>
{{/em-form}}
```
submitButton=false, no action and a button with type='submit'
```
{{#em-form model=model submitButton=false as |form|}}
  ...
  <button type='submit'>
    Submit
  </button>
{{/em-form}}
```

**Comment by GCorbel** [comment]
You're right, this is a bug. I'm very sorry for that. It was a big refactoring and I did some mistakes.

Let me know if you have other problems.

Do you want to do a PR ? I can do it if you don't want.

**Comment by slannigan** [comment]
If you have time to look at it within the next day, that'd be great, since you know more about the context and probably have a better idea of how to fix it. If you don't have time I'd be happy to take a look!

**Comment by GCorbel** [comment]
I'll do it. It should not be complicated.

**Comment by GCorbel** [comment]
I created #161 . It should fix the issue Please, can you test it ? I will merge once I have your confirmation.

**Comment by slannigan** [comment]
I tested https://github.com/piceaTech/ember-rapid-forms/pull/161 against my test repo (https://github.com/slannigan/em-forms-refactor-bug), and unfortunately the last two forms are still causing the page to refresh on submit!

**Comment by spruce** [comment]
I will wait to merge the PR until this is fixed, ok @GCorbel ?

**Comment by GCorbel** [comment]
@slannigan @spruce I'll check it tonight.

**Comment by slannigan** [comment]
Ok, thanks! If I can be of help let me know.

**Comment by GCorbel** [comment]
It works now. I tried with your project but please, give me a confirmation.

Don't forget to replace the version with `    "ember-rapid-forms": "https://github.com/GCorbel/ember-rapid-forms/tarball/6804704853127521c72f8814741d88a40e72fe36"` in your package.json.

**Comment by slannigan** [comment]
I tested `"https://github.com/GCorbel/ember-rapid-forms/tarball/6804704853127521c72f8814741d88a40e72fe36"` against many of our site's forms, and it works great! Thanks for your fix!

**Comment by GCorbel** [comment]
awesome. I'll merge the PR and I close this issue.
