### ISSUE TITLE
em-select not initialized to existing value

### ISSUE THREAD

**Issue by technomage** [piceaTech/ember-rapid-forms#170]
When a template is presented that contains an em-form and within that an em-select the value in the model is not used to initialize the em-select display. When the form is presented it clears the value of the property.

When em-select is initialized it looks at the selectedIndex of the component but not at the existing value in the model.  The selectedIndex is generally 0 on an uniniitalied select box and so it sees a selection against the prompt and clears the property value, rather than initializing the select box to the value already in the model.

**Comment by GCorbel** [comment]
Can you check #169 ? I think it will resolve your problem.

**Comment by technomage** [comment]
I have reworked the design, but will test in the near future.

**Comment by technomage** [comment]
This resolves the issue.
