### ISSUE TITLE
Compile Error: fa-icon is not a helper in version 1.2

### ISSUE THREAD

**Issue by jgoclawski** [piceaTech/ember-rapid-forms#179]
After updating to 1.2 I'm getting: `Uncaught Error: Compile Error: fa-icon is not a helper`.
The stacktrace is not meaningful, but I've seen `formComponent.validationIcon` in debugger, which seems to be related to this PR: #175.
I had to downgrade to 1.1.0, where everything works.

**Comment by spruce** [comment]
Thanks for the report. 
That seems to be the case. I gonna upgrade my own usage today and fix that problem and let you know as soon as I found something

**Comment by spruce** [comment]
Currently I have a PR open at https://github.com/martndemus/ember-font-awesome/pull/186 which should resolve the current problem with this. Gonna figure it out tomorrow.

**Comment by spruce** [comment]
Hey,
I just made a beta version of ERF containing the fix mentioned above. Could you try the beta? (Is on npm as ember-rapid-forms@1.2.4-beta.0 )

Thanks.

**Comment by spruce** [comment]
Closing: Should be fixed with 1.2.4.
