### ISSUE TITLE
forEach error during ember-server, caused by ember-font-awesome

### ISSUE THREAD

**Issue by toovy** [piceaTech/ember-rapid-forms#181]
Hi,
with ember(-cli) 2.16.2 `ember server` gives me an error. I could track it down to ember-font-awesome that needs > v4.0.0 with newer ember-(cli) versions. In my fork I fixed it by just updating the version number of ember-font-awesome, but as I don't know anything about the implications I just wanted to report.
BR toovy

**Comment by spruce** [comment]
Thanks for reporting.
Is it the same error as #179 ? I'm already working to fix that. I made a PR over at ember-font-awesome. Should be fixed in the next few days.

**Comment by riklaunim** [comment]
node_modules/ember-rapid-forms/node_modules/ember-font-awesome/index.js 113:30 -- seems like dependencies still require FA 3.0 instead of 4.0 even when I have 4.0 in my package.json.

**Comment by spruce** [comment]
Hey,
I just made a beta version of ERF containing the fix mentioned above. Could you try the beta? (Is on npm as ember-rapid-forms@1.2.4-beta.0 )

Thanks.

**Comment by artsyca** [comment]
The beta is working with `ember s`

**Comment by spruce** [comment]
Closing: Should be fixed with 1.2.4.
