### ISSUE TITLE
Ember 3.0.0 Deprecation - run.schedule('sync')

### ISSUE THREAD

**Issue by slannigan** [piceaTech/ember-rapid-forms#189]
As of Ember 3.0.0, this deprecation warning appears when using `em-select`:

`DEPRECATION: Scheduling into the 'sync' run loop queue is deprecated. [deprecation id: ember-metal.run.sync`
https://puu.sh/zwi3l/659ca974f3.png

The issue is the `run.schedule('sync', ...)` here: https://github.com/piceaTech/ember-rapid-forms/blob/master/addon/components/em-select.js#L41

I'm happy to help to write a fix. However, the original reason that line of code was added was for support for older versions of Ember: https://github.com/piceaTech/ember-rapid-forms/pull/167/files#r120437420

The comment doesn't say which older versions of Ember were failing. This would be helpful to know.

In situations where I've received warnings like what was described in the above comments, I've usually solved it by using a `run.next`. Would this suffice, or do we need it to run within the same run loop?

Would appreciate input from @GCorbel.

Thanks!

**Comment by GCorbel** [comment]
Hi,

As you can see in the CI, it fails for Ember < 2.9. `run.next` seems to be a good solution. I had some problems with this part of code, with Ember 3, last week. Maybe `run.next` can solve the problem.

Thanks for the report.

**Comment by slannigan** [comment]
Thanks for the help! Submitted a fix: https://github.com/piceaTech/ember-rapid-forms/pull/190
