### ISSUE TITLE
action firing on component initialization expected?

### ISSUE THREAD

**Issue by efx** [piceaTech/ember-rapid-forms#193]
@matthewdorner and I are working on an app that uses this component. We are invoking the component here:
https://github.com/MatthewDorner/hospitalrun-frontend/blob/3ae4115ddf5fefce3a06e12fbbecb81d4b78c521/app/appointments/edit/template.hbs#L31-L40
Is it intentional that the component fires the action on initialization? This behavior surprises me. I would expect the action only to fire when initiated by behavior from within the component.
See https://github.com/MatthewDorner/hospitalrun-frontend/pull/4#issuecomment-381300183 for further background.

**Comment by GCorbel** [comment]
It looks weird and it's not expected. I have to check it a little bit but it's supposed to work as you said. I will try to reproduce the bug tomorrow.

**Comment by GCorbel** [comment]
I did a PR. Can you confirm it solves the bug?

**Comment by MatthewDorner** [comment]
Yeah, that solves it.

**Comment by GCorbel** [comment]
It's merged on the master branch.

**Comment by MatthewDorner** [comment]
Thanks!

**Comment by efx** [comment]
wow, thanks for the rapid turn around @GCorbel !

**Comment by GCorbel** [comment]
No problem, the fix wasn't complicated.

**Comment by efx** [comment]
@GCorbel are you able to release a minor version with this fix so we can target that version?

**Comment by GCorbel** [comment]
I'm not able for the next two weeks. Maybe @spruce can do it.

Le sam. 28 avr. 2018 10:44 AM, Eli Flanagan <notifications@github.com> a
écrit :

**Comment by spruce** [comment]
Released a patch version (1.2.5)
