### ISSUE TITLE
Custom CSS Class on control and label

### ISSUE THREAD

**Issue by abrthel** [piceaTech/ember-rapid-forms#20]
First, thanks for taking over this project. Great work so far. 

It would be nice to be able to customize the CSS classes on the control and label when using just the input component. 

So something like 
```
{{ em-input
  label="Test Label"
  property="test-label"
  controlWrapper = "col-md-6"
  labelClass= "col-md-4"
}}
```
would output like
```
<div class="form-group">
    <label class="control-label col-md-4">Company Name</label>
    <div class="col-md-6">
        <input class="form-control" type="text">
    </div>
</div>
```

**Comment by pedrokiefer** [comment]
I'll take a look on this soon. I'm focusing on cleaning up and adding tests right now. I still need to create unit tests for `em-input`, but once I do this adding custom CSS classes should be really easy. 

The documentation also needs some love. Most components have some non-documented properties.

**Comment by pedrokiefer** [comment]
@abrthel I've pushed support for this. Still need to update the docs.
