### ISSUE TITLE
Update bootstrap

### ISSUE THREAD

**Issue by pedrokiefer** [piceaTech/ember-rapid-forms#22]
Newer bootstrap has a different markup for handling validation icons.

This PR implements that: https://github.com/indexiatech/ember-forms/pull/86/files
After merging this we can update bootstrap to 3.3.

**Comment by haldiggs** [comment]
did this ever get done?

**Comment by GCorbel** [comment]
I think it's correct like it is right now. Fill free to reopen the issue if I'm wrong.
