### ISSUE TITLE
Update model bindings

### ISSUE THREAD

**Issue by limptwiglet** [piceaTech/ember-rapid-forms#29]
Hello,

I have notice that updating the model attribute on forms dosnt update the actual form inputs. I noticed that this was an issue on ember-forms repo and a PR has been merged that fixes this:

https://github.com/indexiatech/ember-forms/pull/92

Is there any chance of getting this merged?

Thanks

**Comment by pedrokiefer** [comment]
This should be already fixed. At least `InFormMixin` is observing changes on `form.model`. It might not be cleaning the previous form errors showing on the inputs, is this your issue? If it's, I just need to add a new test case for this, and the fix should be easy.

**Comment by limptwiglet** [comment]
@pedrokiefer this wasnt my issue but something that I have come across.

I just added the lines here: https://github.com/indexiatech/ember-forms/pull/92/files#diff-fa2e9f8a9e51e50c7357b8c53e619cbaR20 and it seems to be working fine.

**Comment by pedrokiefer** [comment]
@limptwiglet this lines here? Those are the only one that aren't on rapid-forms yet.

```javascript
canShowErrorsObserver: (function () {
  this.set('canShowErrors', false);
}).observes('form', 'form.model'),
```

**Comment by limptwiglet** [comment]
My bad @pedrokiefer my package version was locked to 0.6.2 and I noticed these lines are in 0.7.0. Sorry for wasting your time!

**Comment by pedrokiefer** [comment]
@limptwiglet not a problem, I've just added the missing observer, now the form hides any validation until the user do something to it again.
