### ISSUE TITLE
make future proof

### ISSUE THREAD

**Issue by spruce** [piceaTech/ember-rapid-forms#3]
https://gist.github.com/samselikoff/1d7300ce59d216fdaf97

See: https://github.com/indexiatech/ember-forms/issues/94

**Comment by pedrokiefer** [comment]
Could we try to list what we need to change? From the top of my head I only know that we have to cleanup the deprecation messages when running on canary.

**Comment by spruce** [comment]
That sounds right. Other thing I had in mind was data down, actions up. That we follow that paradigm.

**Comment by spruce** [comment]
We should use the `mut` helper to change the values and not binding to them

**Comment by spruce** [comment]
I think we don't need to do this. Since we would have the same affect and no clear benefit
