### ISSUE TITLE
ember-cli 0.2.6 deprecation warning

### ISSUE THREAD

**Issue by ezpuzz** [piceaTech/ember-rapid-forms#32]
```
[Deprecated] this.pickFiles is deprecated, please use broccoli-funnel directly instead  [addon: ember-rapid-forms]
```

**Comment by pedrokiefer** [comment]
Thanks for reporting this! I've just pushed a fix.

BTW, ember-cli 0.2.6 changed some behaviour on the `Brocfile.js`, i'll have to check if using broccoli-funnel here makes sense. As I understand, things you want to be included in the `App`, must go on `index.js`, brocfile only handles things for the *dummy* app.
