### ISSUE TITLE
Em-checkbox not working

### ISSUE THREAD

**Issue by Kuzirashi** [piceaTech/ember-rapid-forms#36]
See here - http://piceatech.github.io/ember-rapid-forms/#/overview - try clicking checkbox for `Active` property. You'll see that value of `Active` isn't updated.
![trello11](https://cloud.githubusercontent.com/assets/4950658/8005164/28bf125a-0b87-11e5-85e6-c41d44420666.png)

Same happens in my application. In ember-idx-forms I needed to use empty label and it worked, but since I switched to ember-rapid-forms it doesn't work. My code:
`{{em-checkbox property="rulesAccept" label=" "}}`
But I guess since example on your page doesn't work my code isn't needed. I'm waiting for this fix.

Edit:
Using standard ember input helper works:
`{{input type='checkbox' checked=model.rulesAccept }}`

**Comment by pedrokiefer** [comment]
I'll try to work on this issue later today. Really strange behaviour, it was supposed to be working!
What version of ember are you using?

**Comment by Kuzirashi** [comment]
1.13.0-beta.2 @pedrokiefer
