### ISSUE TITLE
Type="submit" attribute missing from em-form-submit

### ISSUE THREAD

**Issue by wvteijlingen** [piceaTech/ember-rapid-forms#38]
The em-form-submit component has a `type` property with value `submit`, but its template doesn't contain the type attribute.

**Comment by pedrokiefer** [comment]
Ops!! I'll fix and make sure we have a test for it. Thanks for the report.

**Comment by pedrokiefer** [comment]
I've pushed a fix, but the test is failing on phantomjs. No problem when running on chrome.

**Comment by spruce** [comment]
Fixed with 09814f65f2a5b35b18e20a5a89c2142c672d1a35
