### ISSUE TITLE
em-select Errors without optionValuePath & optionLabelPath

### ISSUE THREAD

**Issue by xcskier56** [piceaTech/ember-rapid-forms#40]
If you pass a standard array of options to `em-select` it throws a `Uncaught TypeError: Cannot read property 'indexOf' of undefined`

Example Code:

    // ==== test.coffee ====
    `import Ember from 'ember'`

    TestComponent = Ember.Component.extend
      testOptions: Ember.A(['opt1', 'opt2', 'opt3'])
      testOptions2: Ember.a([
        {label: 'opt1', value:'opt1'}
        {label: 'opt2', value:'opt3'}
        {label: 'opt3', value:'opt3'}
      ])
    
    `export default TestComponent`

    // ==== test.emblem ====
    // The first select fails, the second & third selects work.
    .div
       em-form model=model action='action'
         em-select property='name' label='Name' content=testOptions prompt='Choose a Name'
         em-select property='name' label='Name' content=testOptions optionValuePath='content.value' optionLabelPath='content.label' prompt='Choose a Name'
    .div
       view 'select' content=testOptions

**Comment by pedrokiefer** [comment]
`testOptions2` seems to be defined as Ember.**a** and I think the correct should be Ember.**A**. But that should not trigger any error, as you are using `testOptions` on your tests. 

Which version of ember are you using?

**Comment by spruce** [comment]
With 0.8.0-alpha2 it should be fixed.
https://github.com/piceaTech/ember-rapid-forms/blob/fix-ember-1.13/addon/components/em-select.js#L26

Can You please test it?

**Comment by spruce** [comment]
Gonna close it as it is stalling and should be fixed. Reopen if that is not true
