### ISSUE TITLE
differences

### ISSUE THREAD

**Issue by beastmst** [piceaTech/ember-rapid-forms#41]
hi, can someone please explain to me the ember-rapid-forms and ember-forms, what are the differences?  why you guys need to fork a new project from the original codes.

in addition, how can i write a server validator (eg, email unique check from server) on a text field only if the field is lost focus (it means the user done for entering) ? 

thanks

**Comment by technomage** [comment]
The fork was to be compatible with ember-cli and the latest version of ember after the original project was dormant for several months and the maintainer would not allow anyone to make commits.

**Comment by pedrokiefer** [comment]
We still wish to be compatible with the last version of ember, but lots of things changed and more will change in the next few months. I'm waiting to see what happens to the RFC mentioned on #39 and make the necessary changes.

**Comment by beastmst** [comment]
ok, thanks.. now i got a clearer pic on this fork...

**Comment by spruce** [comment]
Closing now
