### ISSUE TITLE
`cid` attribute not working

### ISSUE THREAD

**Issue by joshpfosi** [piceaTech/ember-rapid-forms#42]
I am trying to set either the `name` or `id` of the input field generated by `{{em-input}}` using the `cid` tag and it is entirely dysfunctional as far as I can tell.

Is this correct usage:

```hbs
{{#em-form model=this submitButton=false}}
  {{em-input property="identification" cid="email"    type="email"    placeholder="Enter your email"}}
{{/em-form
```

**Comment by spruce** [comment]
Yes it is correct usage as far as I can tell. :)
I think we got a bug there. 

Quickfix for now editing `node_modules/ember-rapid-forms/addon/templates/components/em-form-group.hbs` line 8 changing it to
```
cid=cid validationIcons=validationIcons mainComponent=this}}
```

I gonna release a new version instantly.

Thanks for the observation. Never used this feature myself :)

**Comment by joshpfosi** [comment]
Hmm this doesn't seem to fix the issue :(

**Comment by spruce** [comment]
Are you sure that you have the latest version(0.7.1)?

**Comment by joshpfosi** [comment]
Yes. I also confirmed the hotfix you applied was present.

**Comment by joshpfosi** [comment]
So I think this is actually the problem: Line 19 of `node_modules/ember-rapid-forms/addon/templates/components/form-group-control.hbs` needs to be changed, as well, to

```hbs
      cid=cid validationIcons=validationIcons mainComponent=this}}
```

This resolved the issue.

**Comment by joshpfosi** [comment]
Are you going to release this soon?

**Comment by spruce** [comment]
https://github.com/piceaTech/ember-rapid-forms/releases/tag/v0.7.2

**Comment by asermax** [comment]
Question: was the `cid` attribute removed from the latests betas? 
If it was, is there any chance they will be reintroduced? We're currently depending on it to run acceptance tests (it's a lot easier to look for fields in form using an id) and we would like to move out from idx-forms to rapid-forms but after giving the code a quick look, I didn't find them :(

**Comment by spruce** [comment]
Now it should be working again with 1.0.0-beta4. Was removed by accident. need to add test for that

**Comment by asermax** [comment]
Sorry for the late response. The changes indeed fix the `cid` for text inputs, but it seems that it still isn't working for other controls, like the select. I will put together a pull request to try to add those if you don't mind.

**Comment by spruce** [comment]
I merged that. Thanks for the PR.
