### ISSUE TITLE
Ember 1.13 deprecations.

### ISSUE THREAD

**Issue by koryteg** [piceaTech/ember-rapid-forms#43]
getting this in the console:
Accessing `template` in <dashboard@component:em-input::ember2708> is deprecated. To determine if a block was specified to <dashboard@component:em-input::ember2708> please use `{{#if hasBlock}}` in the components layout.

I was going to work on a PR but this looks like a big change.

**Comment by spruce** [comment]
I'm currently working on that. See https://github.com/piceaTech/ember-rapid-forms/pull/44

Have you got any more related deprecations? Please report them on the PR. Thanks

**Comment by spruce** [comment]
Should be fixed in 0.8.0-beta2. Can You please verify that?

**Comment by spruce** [comment]
Closing as it is stalling and should be fixed. Please reopen if thats not correct.

**Comment by koryteg** [comment]
sorry for not getting back. notifications get lost sometimes. but this is fixed. thanks
