### ISSUE TITLE
Cursor position error in em-input

### ISSUE THREAD

**Issue by katarzynajaskolska** [piceaTech/ember-rapid-forms#48]
When I add an em-input inside an em-form, type some text, move the cursor to the middle of the text and try to type more text, cursor automatically jumps to the end of the text. 

https://v.usetapes.com/uA83Hodbju

This only happens when model is specified like this:
```
{{#em-form model=this}}
  {{em-input}}
{{/em-form}}
```
When I set model as a string, it works fine.

This problem only appears in versions 0.8.0-alpha2 and 0.8.0-beta2.

**Comment by spruce** [comment]
Thanks for the bug report. I've got a idea what it might be. I will look into that tomorrow

**Comment by spruce** [comment]
The problem is that the value gets set after every keystroke which makes the cursor be moved to the end of the input field. That was what I did expect. Currently searching for a solution

**Comment by spruce** [comment]
Can You please test with version ember-rapid-forms@0.8.0-beta3 ?

**Comment by katarzynajaskolska** [comment]
Now it works perfectly. Thanks for help!
