### ISSUE TITLE
A helper named 'eq' could not be found with em-select

### ISSUE THREAD

**Issue by GCorbel** [piceaTech/ember-rapid-forms#49]
Hello,

I use this helper in a template : 

    {{em-select content=all_skills}}

I don't find with `eq` helper is called.

Any idea?

**Comment by spruce** [comment]
Which version of ember-rapid-forms are you using? 0.8.0-{alpha|beta} ?

It reads as if you didn't install ember-truth-helpers.

You have to follow the the Installation guide of the branche fix-ember-1.13 from where the version 0.8.0 will be released:
https://github.com/piceaTech/ember-rapid-forms/tree/fix-ember-1.13#installation--tutorial

**Comment by GCorbel** [comment]
You're right.
