### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined when I type something on a textarea.

### ISSUE THREAD

**Issue by GCorbel** [piceaTech/ember-rapid-forms#50]
Hello,

I have this controller :

    export default Ember.Controller.extend
      newMessage:(->
        @store.createRecord('message')
      ).property('newMessage') 

And this template : 

      {{#em-form model=model}}
        {{em-text canShowErrors=true property="body"
          label="Body" placeholder="Type a message"
          class="body"}}
      {{/em-form}}

And this model : 

    export default DS.Model.extend
      body: DS.attr('string')
      trail_id: DS.attr('string')
      trail: DS.belongsTo('trail')
      created_at: DS.attr('string')

Each time I type something in the form, I always have "Cannot read property 'value' of undefined" at [this line](https://github.com/piceaTech/ember-rapid-forms/blob/master/addon/components/html-text.js#L17).

I think the reason is because `this.$('input')[0];` returns `undefined`. The field is not an input but a textarea.

Thanks for your help.

**Comment by spruce** [comment]
Damn. Did forget to upload my change. I did also run into that problem will be solved soon (like 2 h)

**Comment by spruce** [comment]
Please try again with version 1.0.0-beta2

**Comment by GCorbel** [comment]
It works. Thanks.
