### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined with em-select

### ISSUE THREAD

**Issue by GCorbel** [piceaTech/ember-rapid-forms#51]
Hello,

I have this simple select : 

      {{em-select content=allSkills prompt="Select Skill"}}

The select tag is created succesfully with the right data but, once I click on a value, I have this error : 

    Uncaught TypeError: Cannot read property 'id' of undefined with em-select at [this line](https://github.com/piceaTech/ember-rapid-forms/blob/47e95af20fadbdccba83c4ed4d96ebd72d3930b4/addon/components/html-select.js#L39).

Here is the data in `allSkills` in JsonAPI format : 

    {"data":[{"id":"1","type":"skills","attributes":{"name":"Rails","description":null,"link":null}}]}

Is there something to do?

**Comment by spruce** [comment]
Yes, You have to have an array which is formated like this:
```
[{id:'asd', value: "this should be shown"}, {id:'no', value:'nothing to show'}]
```

See controller code on http://piceatech.github.io/ember-rapid-forms/#/controls/select (note: template markup is out of date and will be replaced soon)

**Comment by GCorbel** [comment]
I have another bug with "content.id". "." is not allowed. I have not the error right now. I will post it later.

**Comment by spruce** [comment]
right. with the new versions (0.8 and 1.0 beta you don't prefix 'content.' just use the name which should be 'id' and 'value' but if you use these two you don't have to specify them they are the standard )

**Comment by GCorbel** [comment]
It works. I prefer to pass directly an array of models. It's strange to have to convert models in another format.

Thanks!

**Comment by spruce** [comment]
@GCorbel then please open a issue asking for the change. There we can discuss it.
