### ISSUE TITLE
Use the array of record instead a conversion with `em-select`

### ISSUE THREAD

**Issue by GCorbel** [piceaTech/ember-rapid-forms#52]
Hi,

With `em-select`, we have to have an array like this `[{id: 1, name: 'Value 1'}, {id: 2, name: 'Value 2'}]` so, if we find records like this `this.store.findAll('users')`, we have to a loop that convert each value and keep it in an array. I think it should be better to use the array of models directly.

**Comment by spruce** [comment]
Have you a nice code example on how to do that? Can You please elaborate more. Definitely interested

**Comment by GCorbel** [comment]
This is my template : 

    <div class="panel panel-default">
      <div id="name" class="panel-heading">Add a new skill</div>
      <div class="panel-body">
        {{#em-form model=skillUser}}
          {{em-select canShowErrors=true label="Skill" property="skill_id"
            content=allSkills optionValuePath="id"
            optionLabelPath="name" prompt="Select Skill"}}
      </div>
    </div>

And the controller : 

    export default Ember.Controller.extend
      allSkills: (->
        @get('skills').then (data) =>
          skills = for skill in data.toArray()
            skill.getProperties(['id', 'name'])
          @set('allSkills', skills)
      ).property('allSkills')
      actions:
        submit: ->

As you can see, I have to extract `id` and `name`. It can be better to users the record directly.

**Comment by jkleinsc** [comment]
I am running into this issue as well and perhaps I can add some additional input:
In [ember-forms](https://github.com/indexiatech/ember-forms), you could use a string array as the content for a select:
Controller:
```javascript
myarray: ['one','two','three','four']
```
Template:
```handlebars
{{em-select content=myarray optionValuePath="content" optionLabelPath="content"}}
```
Because ember-rapid-forms is using the get helper behind the scenes, there isn't currently any way to tell em-select that both the value and label should use the value of each array item vs a property on each item in the array.

**Comment by nobesnickr** [comment]
I have a pull request in right now that should address and allow for this. Hung up on getting tests implemented but hopefully this will be available for you soon.

https://github.com/piceaTech/ember-rapid-forms/pull/54
