### ISSUE TITLE
Fixes for ember 2.0 

### ISSUE THREAD

**Issue by brisc** [piceaTech/ember-rapid-forms#56]
Ember-validation was updated to support ember 2.0 .
Ember-rapid-forms should use ember-validation 2.0.0-alpha.4 instead of alpha 3 (Ember Enumerable Utils were removed in 2.0 )
- [x] upgrade ember-validation to 2.0.0-alpha.4

**Comment by spruce** [comment]
It's done in c46724b7fad2bba6c411a995305e9ff2d5ee7485 isn't it?

**Comment by spruce** [comment]
Stalling and seems fixed. Closing now. If not ok with that. Just reopen.
