### ISSUE TITLE
Demo menu is broken

### ISSUE THREAD

**Issue by spruce** [piceaTech/ember-rapid-forms#57]
Btw. you know that your demo is broken? If you click on a menu element the menu disappears...
Noticed by @wzrdtales

**Comment by GCorbel** [comment]
Hi,

For christmas, I decided to contribute to this project by fixing bugs on the documentation.

I'm trying to serve the dummy app with `ember serve`. First of all, I had to create an empty Brocfile.js. Now, I want have this message :

    Invalid tree found. You must supply a path or an object with a `.read` (deprecated) or `.rebuild` function: Object
    Error: Invalid tree found. You must supply a path or an object with a `.read` (deprecated) or `.rebuild` function: Object
        at readAndReturnNodeFor (/app/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:90:13)
        at /app/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:42:14
        at lib$rsvp$$internal$$tryCatch (/app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
        at lib$rsvp$$internal$$invokeCallback (/app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
        at /app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1001:13
        at lib$rsvp$asap$$flush (/app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
        at doNTCallback0 (node.js:408:9)
        at process._tickCallback (node.js:337:13)

There is a similar issue here : https://github.com/indexiatech/ember-idx-tabs/issues/16.

I think something is deprecated. I will try to fix this issue but let me know if you have the solution.

**Comment by GCorbel** [comment]
I found the solution. I still have problem with css but I will solve it.

**Comment by spruce** [comment]
I think it is ok, that the Brocfile is not created.
For more info see here: https://github.com/ember-cli/ember-cli/blob/master/TRANSITION.md#brocfile-transition

**Comment by GCorbel** [comment]
I forgot to give the link to the PR : https://github.com/piceaTech/ember-rapid-forms/pull/64

**Comment by GCorbel** [comment]
I don't understand but I had a bug last week and add the Brocfile fix it. Now, it works with the master branch.

I will close this issue and rebase my PRs.
