### ISSUE TITLE
em-select docs incorrectly show use of content. in optionValuePath and optionLabelPath

### ISSUE THREAD

**Issue by drewnichols** [piceaTech/ember-rapid-forms#59]
after upgrading my app to Ember 2.1 and upgrading to ember-rapid-forms 1.0.0-beta3 none of my select boxes had any values in them. After some debugging I found that i needed to remove the `content.` prefix to the optionValuePath and optionLabelPath properties. 

It seems that the documentation in the [demo app](https://github.com/piceaTech/ember-rapid-forms/blob/v1.0.0-beta3/tests/dummy/app/templates/controls/select.hbs) does not reflect this change yet.

**Comment by drewnichols** [comment]
submitting https://github.com/piceaTech/ember-rapid-forms/pull/60 with fix

**Comment by spruce** [comment]
Thanks for PR and finding that out
