### ISSUE TITLE
Running application test leads to error

### ISSUE THREAD

**Issue by spruce** [piceaTech/ember-rapid-forms#6]
See: https://github.com/indexiatech/ember-forms/issues/87
templateName is deprecated ( https://github.com/ember-cli/ember-cli/issues/3510)

**Comment by technomage** [comment]
I have the issue with layoutName resolved.  It requires that the component names from app/components be used for the addon/ matching classes in order to find the templates.  But, the use of partials is still making the tests fail.  I also note that the project itself has no tests, which would expose some of these issues as well.

I will be making the existing partial into components so that tests can use these components.  Please advise if there are any issues with this, as I would prefer not to keep a permanent fork.

**Comment by technomage** [comment]
I anticipate having a pull request late today.  To make it work most of the files have been moved and renamed on the add-on side and templates are now under addon.  So, it will be a pretty extensive PR.

**Comment by spruce** [comment]
I will review the PR later today. But as far as what I've seen so far it looks good :+1:

**Comment by spruce** [comment]
After landing #12 we should test if this is still a problem

**Comment by pedrokiefer** [comment]
Is this still an issue?

**Comment by spruce** [comment]
I don't think it is. Will test it after cleaning up my tests on the application. Should be later today.

**Comment by spruce** [comment]
Now it's failing in a new way:
```
            Died on test #2 	at test (http://localhost:7357/assets/test-support.js:1803:15)
            	at http://localhost:7357/assets/project.js:16207:19
            	at http://localhost:7357/assets/vendor.js:150:34
            	at tryFinally (http://localhost:7357/assets/vendor.js:30:21)
            	at requireModule (http://localhost:7357/assets/vendor.js:148:15)
            	at require (http://localhost:7357/assets/test-loader.js:29:16)
            	at loadModules (http://localhost:7357/assets/test-loader.js:21:25)
            	at load (http://localhost:7357/assets/test-loader.js:40:35)
            	at http://localhost:7357/assets/test-support.js:5578:20: Assertion Failed: A helper named 'form-group' could not be found
```

**Comment by pedrokiefer** [comment]
Try adding `'component:form-group'` the `needs` attribute.

**Comment by spruce** [comment]
That works for form-group but then it raises the error with em-form-label. 

Got the same problem with models which depend on one another. There I had to include one model everywhere. That can't be the solution to include every component we depend on in test which use ember-forms. Right?

**Comment by pedrokiefer** [comment]
@spruce I think there is an open bug on ember-cli / ember-cli-qunit for improving the loading of dependency in tests. The same thing happens when a model has relationships, you have to add all the relationships __recursively__ to the `needs` attribute.

**Comment by spruce** [comment]
Damn. did read it to late. Gonna search for the issue and close mine then

**Comment by technomage** [comment]
I strongly recommend moving to the new component integration tests.  They handle a lot of this, and you use a template to specify the component arguments, which makes API docs and tests align.

**Comment by spruce** [comment]
Fixed as @technomage comment
