### ISSUE TITLE
Not able to display errors with canShowErrors

### ISSUE THREAD

**Issue by GCorbel** [piceaTech/ember-rapid-forms#62]
Hello,

I have this form in a template : 

      {{#em-form model=model submitButton=false}}
        {{em-input value=email canShowErrors=true}}
      {{/em-form}}

When the model has errors, errors are not displayed. I added this : 

        {{#each model.errors.email as |error|}}
          {{error.message}}
        {{/each}}

And it works. How to display errors in inputs? It's not clear in the doc. I think the documentation can be improved.

**Comment by GCorbel** [comment]
I was wrong. It works when I use `em-input` correctly.

**Comment by spruce** [comment]
The docs definitely can be improved. Can you be a little more specific?

**Comment by GCorbel** [comment]
It can be useful to add the code for each forms. I didn't see something about the `canShowErrors` options.
