### ISSUE TITLE
Not able to work with em-select

### ISSUE THREAD

**Issue by GCorbel** [piceaTech/ember-rapid-forms#63]
Hello,

I have many problems with `em-select`. I have this form : 

      {{#em-form model=model submitButton=false}}
        {{em-select label="User" property="user" content=users
          prompt=" " optionValuePath="id" optionLabelPath="email"}}
      {{/em-form}}

In the controller I have this : 

    import Ember from 'ember';

    export default Ember.Controller.extend({
      users: function() {
        return this.store.findAll('user');
      }.property('users')
    });

I have this message `Cannot read property 'id' of undefined` at [this line](https://github.com/piceaTech/ember-rapid-forms/blob/master/addon/components/html-select.js#L37). I replaced it by `const selectedValue = content.objectAt(selectedIndex);` and go one step further. I have no error but I have not result when I do that : 

      console.log(this.controller.model.get('user.id'));

Furthermore, there is a problem on [the doc](http://piceatech.github.io/ember-rapid-forms/#/controls/select). Labels are blank.

Thanks for your help!

**Comment by spruce** [comment]
Thanks for reporting that. Which Versions are you on?

**Comment by GCorbel** [comment]
Hi and sorry for the late answer.

It's weird but it works. Thanks for your work.

**Comment by spruce** [comment]
BTW: I have pushed a change that was already in master but not on the github page
