### ISSUE TITLE
Select belongsTo associaton

### ISSUE THREAD

**Issue by GCorbel** [piceaTech/ember-rapid-forms#68]
Hi,

I'm looking for a simple way to do a selection on a belongsTo association. I tried to do this : 

        {{em-select label="User" property="user" content=users
          prompt=" "
          optionValuePath="id" optionLabelPath="id"}}

with this model : 

    import DS from 'ember-data';

    export default DS.Model.extend({
      userId: DS.attr(),
      user: DS.belongsTo('user'),
      course: DS.belongsTo('course')
    });

And it does not work.

I have to assign the userId and retrieve the user after. It can be useful to have directly.

What you think?

**Comment by apokinsocha** [comment]
not enough info here. however, what I can tell you is that you need to have "users" on the parent controller (or component) as an array of objects. each object should have for example "id" and "name" keys in your case. the latter "name" will be used as the labelpath, and id will be the idpath.
that means that you should probably fulfill that promise for the "users" when you get to that route, and assign it to a controller (on setupController, or however you're setting it).
for keeping track of the current user, you can set a "currentUser" (so property="currentUser") on the controller as well.
and then have an observer which changes the "user" property on the model when the "currentUser" changes. but I think it may work with just "user".
that would be one way of doing it.

**Comment by GCorbel** [comment]
@apokinsocha , I understand your solution but it can be nice to have a solution built in Ember Rapid Form. To do it "manually" can be tedious.

**Comment by GCorbel** [comment]
My users are provided by `this.store.findAll('user')`.

**Comment by apokinsocha** [comment]
ah okay, didn't know you wanted a built-in solution. I think it's possible to add this feature and could be a good idea, but then you have probably to consider supporting different types of relationships Ember data. and it's possible someone is using their own custom data adapters. 
and there are many possible implementations when it comes to rendering selects and how interact with your app. i wouldn't say adding one or two attributes and a observer is tedious work, but each to their own. to making this api ember and app neutral it's probably better to leave it as is, imho.

**Comment by GCorbel** [comment]
I think [emberx-select](https://github.com/thefrontside/emberx-select) is doing it nicely. For custom behaviour, it's always possible to do code from scratch. The idea is to be as in [simple_form](https://github.com/plataformatec/simple_form).

**Comment by GCorbel** [comment]
At [this line](https://github.com/piceaTech/ember-rapid-forms/blob/master/addon/components/html-select.js#L38) we have an attribute of the selected data. What about checking if the optionValuePath is defined. If it is, we are keeping the same behavior. If it's undefined, we can simply do this `selectedID = selectedValue`.

What you think ? The opinion of @spruce is welcome.

**Comment by apokinsocha** [comment]
you maybe trying to do different than I thought...

**Comment by GCorbel** [comment]
I did this : 

        var selectedID;

        if (optionValuePath == 'this') {
          selectedID = selectedValue;
        } else {
          selectedID = selectedValue[optionValuePath];
        }

It seems to work. I think it can be clearer with a better name or option. Do you have an idea ?

**Comment by spruce** [comment]
I'll check this issue in a bit. Holidays are creating a mess for me. Sorry for taking so long

**Comment by spruce** [comment]
How excactly are you trying to call the select?
Gonna close #54. Than
