### ISSUE TITLE
Nested form

### ISSUE THREAD

**Issue by GCorbel** [piceaTech/ember-rapid-forms#69]
I have a form like this : 

    {{#em-form model=model}}
      {{em-select label="Course" property="course" content=courses
        canShowErrors=true prompt=" " propertyIsModel=true optionLabelPath="name"}}
      {{#each model.contacts as |contact|}}
        <div class='row'>
          <div class='col-md-4'>
            {{em-input label="Name" property="contact.name" canShowErrors=true}}
          </div>
          <div class='col-md-4'>
            {{em-input label="Email" property="contact.email" canShowErrors=true}}
          </div>
          <div class='col-md-4'>
            {{em-input label="Phone" property="contact.phone" canShowErrors=true}}
          </div>
        </div>
      {{/each}}
    {{/em-form}}

With this model : 

    import DS from 'ember-data';

    export default DS.Model.extend({
      course: DS.belongsTo('course'),
      contacts: DS.hasMany('contact')
    });

It doesn't work because contact is a relation. It can be useful to have something like `{{#em-fields-for model=contact}}`.

It can also be useful to have a model on inputs like `{{em-input model=contact label="Phone" property="contact.phone" canShowErrors=true}}` this allow to decouple inputs from form.

I'm ready to do a pull request but I need your opinion. What you think?

**Comment by GCorbel** [comment]
I just saw it's already possible. I will clarify the doc.

**Comment by djsegal** [comment]
@GCorbel: what do you mean by its already possible? what docs are you talking about?
