### ISSUE TITLE
Change in model should be reflected in form

### ISSUE THREAD

**Issue by spruce** [piceaTech/ember-rapid-forms#7]
See: https://github.com/indexiatech/ember-forms/issues/82 
and: https://github.com/indexiatech/ember-forms/issues/23

**Comment by xcskier56** [comment]
Just found this fork. Thanks for taking charge! I see that this is open, and a few of the files have changed from the pull request that I submitted to the old repo. Would you like me to update my code and submit a new PR here?

**Comment by spruce** [comment]
Sure. Would be nice.

**Comment by pedrokiefer** [comment]
@xcskier56 if you can wait a little before updating your code, so that we can land #12 to master, that would be awesome.

**Comment by ScottSmix** [comment]
I believe this change may be as simple as adding form.model to the computed property in addon/mixins/in-form.js as follows:

```javascript
...
  model: Ember.computed('form', 'form.model', function() {
    return this.get('form.model');
  })
...
```
@pedrokiefer I know you are talking about doing another commit/merge very soon, could you please include this? I did manually test/debug but did not write any specific tests.

**Comment by pedrokiefer** [comment]
I think I've added a test for this. Can you guys check it, please?

**Comment by joshpfosi** [comment]
I still experience this issue w/ version `0.6.4`.

**Comment by pedrokiefer** [comment]
Can you help me get a test case for this? Right now we have a test case for a property change on a model and it gets changed on the form.

**Comment by joshpfosi** [comment]
I don't have time right now to set up a repo but I can be more specific. I have a form with a newly instantiated model. I populate the form which correctly updates the model. On submission, I save the model and replace the controller attr to which the form is bound with createRecord('model'). This correctly resets the model of the form but NOT of the `{{em-input}}` I'm using in the form. So to set up a test case (if you have the time) you'd need a model with a string attr, a controller with an attr which returns a new instance of this model, and a template which binds an `{{em-form model=newModel}}` and a submit button which saves the model and calls `this.set('newModel', this.store.createRecord('model'))`. This should reproduce the error.

**Comment by pedrokiefer** [comment]
I think something like this should do as a test case, not involving ember-data and controllers. This test case fails with current code.

```javascript
  var component = this.subject({
    targetObject: FormController.create(),
    model: modelA,
    template: Ember.HTMLBars.compile('{{em-input property="name"}}')
  });

  this.render();

  var input = Ember.$(component.element).find('input');
  assert.equal(input.length, 1, "Found input");
  input = Ember.$(input[0]);
  assert.equal(input.val(), 'model-a', "Input has original model value");

  Ember.run(() => {
    component.set('model', modelB);
  });

  assert.equal(input.val(), 'model-b', "Input has new model value");
```

**Comment by pedrokiefer** [comment]
With @ScottSmix change this test case passes. I'll commit this changes, @joshpfosi would you be kind enough to test it?

**Comment by joshpfosi** [comment]
I'd be happy to!

**Comment by joshpfosi** [comment]
Worked like a charm, thank you! When will this be available via `npm install`?

**Comment by pedrokiefer** [comment]
@spruce when can we do a 0.7.0 release?

**Comment by joshpfosi** [comment]
Would it require a minor version bump? Feel like this is more of a bug fix than a feature, but then again I want to now so I'm biased :)

**Comment by pedrokiefer** [comment]
I've also merged some ES6 changes, and renamed all the properties with underscore. The old syntax still works but I'll give a deprecated warning.

**Comment by spruce** [comment]
Sure. I will change the milestone issue to 0.8 then or remove the version number alltogether

**Comment by spruce** [comment]
I think this can be closed then?

**Comment by pedrokiefer** [comment]
:+1:
