### ISSUE TITLE
Changing the layout of the em-select to support disabled attribute

### ISSUE THREAD

**Issue by bluemari** [piceaTech/ember-rapid-forms#74]
Any suggestions on how to extend the em-select component and only change the layout?

**Comment by spruce** [comment]
What exactly are you trying to do? One element of a list should be disabled? If you like you could try to create a PR because I think that has a wide enough applicability.

**Comment by bluemari** [comment]
I want to be able add disabled property to several options inside the select.

**Comment by GCorbel** [comment]
I think, for now, you have to override [this template](https://github.com/piceaTech/ember-rapid-forms/blob/master/addon/templates/components/html-select.hbs) but I don't know how to override an addon with ember.

By the way, a PR is welcomed if you want to contribute.

**Comment by spruce** [comment]
Was added here: https://github.com/piceaTech/ember-rapid-forms/pull/173
