### ISSUE TITLE
Don't directly access property on model

### ISSUE THREAD

**Issue by spruce** [piceaTech/ember-rapid-forms#77]
I think a nice addition would be to be able to directly bind to a value and not necessarily to a property of the model. Like when you want to add a helper which massages the model value somehow (Think converting number of cents to currency displayable value).

How does it sound?

**Comment by GCorbel** [comment]
I agree but it's important to keep the change of properties as simple as possible.

**Comment by spruce** [comment]
Hm. For now I solved it as creating a computed property on the model which does the conversion. Is not extremly nice but works for now.
