### ISSUE TITLE
em-select grouped options

### ISSUE THREAD

**Issue by samsebastian** [piceaTech/ember-rapid-forms#78]
Just an idea, but it would be awesome to be able to use select groups on em-select.

I have a model with a relationship, and I need to use option groups using the top level model, and then selectable options using the relationship.

The way it could potentially work is something along the lines of 

```
// category.js
export default DS.Model.extend({
    title:          DS.attr('string'),
    sort:           DS.attr('number'),
    statuses: DS.hasMany('status')
});

// status.js
export default DS.Model.extend({
    name:          DS.attr('string'),
    sort:           DS.attr('number'),
    statuses: DS.belongsTo('category')
});

```

and then something like the below where the logic would check for the option group properties and recurse down?

```
{{#em-select 
    property="status"
    content=categories
    optionValuePath="id"
    optionLabelPath="name"
    optionGroupLabelPath="title" 
    optionGroupOptions="statuses" }}
```

**Comment by GCorbel** [comment]
It seems to be a very specific case. Feel free to do a pull request. I think it's a nice to have but not an absolute necessity.

**Comment by spruce** [comment]
PR is up at #79

**Comment by spruce** [comment]
Fixed as of https://github.com/piceaTech/ember-rapid-forms/commit/570dffd6f59f6bf7f290e700e445a58af422fea6
