### ISSUE TITLE
Set errors visibility for all fields.

### ISSUE THREAD

**Issue by GCorbel** [piceaTech/ember-rapid-forms#80]
Hi, I just developed this mixin : 

    import Ember from 'ember';

    export default Ember.Mixin.create({
      init: function () {
        this._super();
        this.set('visibleErrors', {});
      },
      showErrors: function() {
        this.changeErrorsVisibility(true);
      },
      hideErrors: function() {
        this.changeErrorsVisibility(false);
      },
      changeErrorsVisibility: function(visible) {
        this.eachAttribute((key) => {
          this.set(`visibleErrors.${key}`, visible);
        });
        this.eachRelationship((key) => {
          this.set(`visibleErrors.${key}`, visible);
        });
      }
    });

This can be use like this : 

    {{em-input canShowErrors=item.visibleErrors.firstName property="firstName"}}

And : 

    validate: function(successCallback) {
        item.validate().then(function() {
          successCallback(item);
        }).catch(function() {
          item.showErrors();
        })
    }

I think it can be useful to add it in ERF. What you think?

**Comment by spruce** [comment]
You Mixin this into your models and have a more fine granual control over where the errors get displayed?

**Comment by GCorbel** [comment]
Yes.

**Comment by spruce** [comment]
Can you elaborate a little on how you then would use it? When do you need to display only some errors? Feel like this is not a too common need. Or am I misunderstanding something?

**Comment by GCorbel** [comment]
I think more precision is needed. When I do : 

    {{em-input canShowErrors=item.visibleErrors property="firstName"}}
    {{em-input canShowErrors=item.visibleErrors property="lastName"}}

If I focus in and out the first field and it's invalid, the second one will be marked as incorrect too. I want to keep the second want normale.

It's the same think with : 

    {{em-input canShowErrors=visibleErrors property="firstName"}}
    {{em-input canShowErrors=visibleErrors property="lastName"}}

With the mixin, errors on field are independent.

**Comment by spruce** [comment]
You don't have to set canShowErrors. That should be handled by ERF automatically. Which shows an error when you focus out and there is actually an error to display.

**Comment by GCorbel** [comment]
Ok but I want to show errors afters validations. Like this : 

    item.validate().then(function() {
      successCallback(item);
    }).catch(function() {
      item.showErrors();
    })

Errors have to be displayed even without focus.

**Comment by spruce** [comment]
Hm. For that use case we only got showErrorsOnRender. But that will display all errors on all fields. if we could manage to merge these two feature it would be great.
I mean if showErrorsOnRender would call showErrors of your mixin. That would make it more flexible which always is good.
