### ISSUE TITLE
Prompt on em-select behaves differently in newer versions

### ISSUE THREAD

**Issue by danconnell** [piceaTech/ember-rapid-forms#83]
Hi,

In older versions of this package, the prompt on em-select was treated as a null value, and if you chose a value then set it back to the prompt, the property would be set back to null. 

This behaviour was changed in this commit: https://github.com/piceaTech/ember-rapid-forms/commit/6455a79ab37c848a2c5ae75a7cbabca52a11defd.

I was wondering if there's any way we could get the old behaviour back? Possibly through a config setting?

Workaround I'm using right now is to not use the prompt setting and just put it in the options themselves.

**Comment by GCorbel** [comment]
I agree. I'll check tonight.

**Comment by spruce** [comment]
I think I also noticed that behaviour in an project myself. But I didn't consider it a bug. But it certainly is. Especially when it was different before.

**Comment by GCorbel** [comment]
Sorry for late answer.I think PR #86 does the correct behavior.
