### ISSUE TITLE
Ability to set canShowErrors on em-* componenents

### ISSUE THREAD

**Issue by danconnell** [piceaTech/ember-rapid-forms#84]
This is a feature request.

It would be nice to be able to set the canShowErrors property to true so that errors can be visible without a user focusing and blurring an input.

The use case for this is: user loads the form, doesn't see error messages, user clicks submit without ever focusing any inputs, user should see error messages.

Looking at the code, it seems like the canShowErrors property is what we should set. It would be nice if this could be set on the em-form or individually on the em-input, em-select, etc.

Thoughts? I could try to do this if it's something you're interested in allowing.

**Comment by GCorbel** [comment]
I think this is is the same think than #80 . Right?

**Comment by danconnell** [comment]
Indeed it is. My bad.

**Comment by GCorbel** [comment]
I'm working on it right now.
