### ISSUE TITLE
How to use with ember data models

### ISSUE THREAD

**Issue by chuckus** [piceaTech/ember-rapid-forms#93]
Hi there,

I am trying to use this add-on with ember data and having trouble trying to validate the form data against a model I have defined.

Following the example on http://piceatech.github.io/ember-rapid-forms/#/getstarted, a model is passed to the template. Seeing as the `model` keyword is already taken on `Ember.Route`, I set it up like this:
```js
//app/routes/signup.js
import Ember from 'ember';
import CreateUser from '../models/create-user';

export default Ember.Route.extend({
  createModel: CreateUser,
});
```
And setup the template like:
```html
{{#em-form model=createModel}}
    {{em-input property="username" label="Email" placeholder="Enter an email..."}}
    {{em-input property="password" label="Password" placeholder="And password..." type="password" disabled=nameHasValue}}
{{/em-form}}
```
The template renders fine but as soon as I start entering text, I get this error and no validation occurs:
```
Uncaught Error: Property set failed: object in path "mainComponent.model" could not be found or was destroyed.
```

How do you correctly pass an ember data model to the template? I am running 1.0.0-beta5.

For reference:
```js
//app/models/create-user.js
import attr from 'ember-data/attr';
import Model from 'ember-data/model';

const CreateUser = Model.extend({
  firstName: attr('string'),
  lastName: attr('string'),
  company: attr('string'),
  username: attr('string'),
  password: attr('string')
});

CreateUser.reopen({
  validations: {
    username: {
      presence: true,
      format: { with: /@/, allowBlank: false, message: 'Must be valid email'  }
    },
    password: {
      presence: true,
      length: {
        minimum: 12
      }
    }
  }
});

export default CreateUser;
```

**Comment by danconnell** [comment]
You need to set the model with `@store.createRecord('create-user')`

**Comment by chuckus** [comment]
@danconnell Thanks, that worked! Still can't get validation to work but the error is gone so going to try figure it out first, new to Ember so just getting my head around it all...

**Comment by danconnell** [comment]
@chuckus You'd need to mixin the EmberValidations.Mixin into your model for the validations to work. See: https://github.com/dockyard/ember-validations
