### ISSUE TITLE
validations do not work

### ISSUE THREAD

**Issue by mkalika** [piceaTech/ember-rapid-forms#94]
Hi,

I am trying Ember Rapid Forms with ember-validations and encounter issue with validations. They simply don't trigger. Here's my model code:

`import DS from 'ember-data';

var PaymentRequest =  DS.Model.extend({
  amount: DS.attr('number'),
  currency: DS.attr('string'),
  paymentTypeId: DS.attr('number'),
  description: DS.attr('string'),
  user: DS.belongsTo('payer')
});

PaymentRequest.reopen({
  validations: {
    amount: {
      presence: true,
      length: {
        minimum: 3
      }
    },
  }
});

export default PaymentRequest;
`

Any help appreciated :) Thx!

**Comment by danconnell** [comment]
You need to mixin the ember validations mixin. Check out the ember validations github: https://github.com/dockyard/ember-validations

**Comment by leoelcoder** [comment]
Try this:

```javascript
    import DS from 'ember-data';
    import EmberValidations from 'ember-validations';

    export default DS.model.extend(EmberValidations,{
        amount: DS.attr('number'),
        currency: DS.attr('string'),
        paymentTypeId: DS.attr('number'),
        description: DS.attr('string'),
        user: DS.belongsTo('payer')

        validations: {
            amount:{
                presence: true,
                length:{
                    minimun: 3
                }
            }
        }
    });
```
You have to install the https://github.com/DockYard/ember-validations project
this I did it using ember-cli

I hope this help you!

**Comment by spruce** [comment]
Thanks for using this addon.

As @danconnell and @leoelcoder said you have to extend from the mixin to get validations to work.

**Comment by mkalika** [comment]
thank you~
