### ISSUE TITLE
Validations not working

### ISSUE THREAD

**Issue by josefguenther** [piceaTech/ember-rapid-forms#95]
I can't get validations to work at all. My problems:
1. It always validates (on leave focus) and turns green, regardless
2. There is no icon present for validation like in the demo

Here's my relevant code:

```
var Content = DS.Model.extend({
  title:     DS.attr('string'),
});

Content.reopen({
  validations: {
    title: {
      presence: true,
      length: {
        minimum: 5,
        maximum: 50,
      },
    }
  }
});
```

```
{{#em-form model=model submitButton=false}}
  {{em-input property="title" label="Title" placeholder="Enter a title..."}}
{{/em-form}}
```

I confirmed that `title` and `validations` are correct properties on the `model` variable. The input gets set correctly.

I also tried installing `ember-validations` and extending in my controller like so:
```
export default Ember.Controller.extend(EmberValidations, {
  validations: {
    'model.title': {
      presence: true,
      length: {
        minimum: 5,
        maximum: 50,
      },
    },
  }
});
```

Which doesn't work either. I also tried embedding the `validations` inside the model without reopening it, with no success. It seems to do the same thing so I really don't understand why the documentation has this (verbose) approach.

Here are the versions of my packages:
```
    "ember-bootstrap": "0.6.4",
    "ember-cli": "2.4.2",
    "ember-data": "^2.4.0",
    "ember-rapid-forms": "1.0.0-beta5",
    "ember-truth-helpers": "1.2.0",
    "ember-validations": "2.0.0-alpha.4",
```

One additional question: is installing `ember-validations` required? or does it install as a dependency automatically? It seemed to make no difference.

**Comment by josefguenther** [comment]
Aha looks like you rely on font awesome for the icon. I added that and solved point 2. It would be worth mentioning in the docs.

Point 1 is still an issue.

**Comment by josefguenther** [comment]
Ok resolved point 1.

I had to extend EmberValidations on my _model_ like so:
```
export default DS.Model.extend(EmberValidations, { ... });
```

This needs to be added to the demo / docs as it is not mentioned anywhere. Only by knowing how `ember-validations` works does this become apparent.

**Comment by GCorbel** [comment]
I close this issue but keep in my than the doc should be improved. It's the second time we had and issue with validation (https://github.com/piceaTech/ember-rapid-forms/issues/94). It's not clear.
