### ISSUE TITLE
ember-validations not working

### ISSUE THREAD

**Issue by haldiggs** [piceaTech/ember-rapid-forms#98]
could just be me, I have added ember-validations as mentioned on the help page. I can see the validations objects but my form still submits without checking. I had assumed I didn't need to manually code for the validations to work. Is there any example of this working other than the [help page here](http://piceatech.github.io/ember-rapid-forms/#/getstarted) ??

**Comment by GCorbel** [comment]
If you use the submit button of Ember Rapid Form, it will be disabled if the model is invalid. If it is not, check what is the result of [this](https://github.com/DockYard/ember-validations#running-validations).

If you don't use the submit button of Ember Rapid Form, there is no special check and you have to handle the submission yourself.

**Comment by haldiggs** [comment]
DockYard describes the validations inside the controller, this seems to make sense but based on the example here I tried reopening the model.

`
    import RalItemClass from '../models/ral-item';

    RalItemClass.reopen(EmberValidations, {
	validations: {
		OrgId: {
			presence: true,
			length: {
				minimum: 5
			}
		},
		UserName: {
			presence: true,
			length: {
				minimum: 2
			}
		},
		Comment: {
			presence: true
		},
		StaledDate: {
			presence: true
		}
	}
    });
`

It seems that every field turns green as I tab through them. One more item though, I am using the ember-power-select drop downs and I don't see anyway to connect them other than an outside validation library. 

I'll keep trying. Thanks for replying.

**Comment by haldiggs** [comment]
ok you are correct, using your button it starts out disabled. Yea!
